default:
  tags: [me4d]

stages:
  - build_and_deploy
  - test

build_and_deploy:
  stage: build_and_deploy
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    - echo -e "migrations and superuser creation needs to be done manually"
    - echo -e "in case docker instances are already running:"
    - docker-compose --env-file ./master.env -f production.yml -p master down
    - docker-compose --env-file ./master.env -f production.yml -p master up --build
  only:
    - master

build_and_deploy:
  stage: build_and_deploy
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    - echo -e "migrations and superuser creation needs to be done manually"
    - echo -e "in case docker instances are already running:"
    - docker-compose --env-file ./dev.env -f production.yml -p dev down
    - docker-compose --env-file ./dev.env -f production.yml -p dev up --build
  only:
    - dev

test:
  stage: test
  needs: []
  script:
    - echo -e "nothing to test yet "
