# Generated by Django 3.0.10 on 2021-06-25 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physicalAddress', models.CharField(blank=True, max_length=1000, null=True)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('descriptions', models.CharField(blank=True, max_length=10000, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True, verbose_name='longitude')),
                ('latitude', models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True, verbose_name='latitude')),
                ('arrivalDate', models.DateTimeField(blank=True, null=True)),
                ('departureDate', models.DateTimeField(blank=True, null=True)),
                ('cleanedDate', models.DateTimeField(blank=True, null=True)),
                ('addressStatus', models.CharField(blank=True, choices=[('notStarted', 'not started'), ('in progress', 'inProgress'), ('cleaned', 'cleaned')], default='notStarted', max_length=20, null=True)),
                ('assigneeID', models.CharField(blank=True, max_length=240, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['updated_at'],
                'get_latest_by': 'updated_at',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['updated_at'],
                'get_latest_by': 'updated_at',
            },
        ),
        migrations.CreateModel(
            name='HealthCareDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('contact_email', models.EmailField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthCareWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=40)),
                ('lastName', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=2000, null=True)),
                ('notificationDate', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthCareWorkers.Case')),
            ],
            options={
                'ordering': ['updated_at'],
                'get_latest_by': 'updated_at',
            },
        ),
    ]
