# Generated by Django 3.0.10 on 2021-06-15 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('healthCareWorkers', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='patients.Patient'),
        ),
        migrations.AddField(
            model_name='address',
            name='cases',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Addresses', to='healthCareWorkers.Case'),
        ),
        migrations.AddField(
            model_name='address',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Addresses', to='patients.Patient'),
        ),
    ]
