# Generated by Django 3.0.10 on 2021-06-25 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('healthCareWorkers', '0002_auto_20210615_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='healthcareWorker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='healthCareWorkers.HealthCareWorker'),
        ),
        migrations.AddField(
            model_name='healthcaredepartment',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthcareworker',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthcareworker',
            name='healthCareDepartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='healthcareWorkers', to='healthCareWorkers.HealthCareDepartment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='healthCareDepartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='healthCareWorkers.HealthCareDepartment'),
        ),
    ]
