# Generated by Django 3.0.10 on 2021-07-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthCareWorkers', '0003_auto_20210625_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='category',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
