# Generated by Django 3.0.10 on 2021-09-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthCareWorkers', '0005_auto_20210815_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressStatus',
            field=models.CharField(choices=[('notStarted', 'not started'), ('in progress', 'inProgress'), ('cleaned', 'cleaned')], default='notStarted', max_length=20),
        ),
    ]
