# Generated by Django 3.0.10 on 2021-06-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20210615_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dengue',
            old_name='changed_by',
            new_name='lastEditor',
        ),
    ]
