# Generated by Django 3.0.10 on 2021-06-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20210625_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dengue',
            name='NS1',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), (None, 'null')], default='', max_length=100, null=True, verbose_name='NS1'),
        ),
        migrations.AlterField(
            model_name='dengue',
            name='UD2',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), (None, 'null')], default='', max_length=100, null=True, verbose_name='UD2'),
        ),
        migrations.AlterField(
            model_name='dengue',
            name='abdominalPain',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), (None, 'null')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dengue',
            name='atypl_d0',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dengue',
            name='bleeding',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), (None, 'null')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dengue',
            name='calfPain',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), (None, 'null')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dengue',
            name='epistaxis',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), (None, 'null')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dengue',
            name='gastrointestinal_bleeding',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), (None, 'null')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dengue',
            name='gum_bleeding',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), (None, 'null')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dengue',
            name='hasFever',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), (None, 'null')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dengue',
            name='hct_d0',
            field=models.CharField(blank=True, choices=[('r0_328', 'r0_328'), ('r328_560', 'r328_560'), (None, 'null')], default='', max_length=100, null=True, verbose_name='UD2'),
        ),
        migrations.AlterField(
            model_name='dengue',
            name='incidencerate',
            field=models.CharField(blank=True, choices=[('incidencerate1', 'incidencerate1'), ('incidencerate2', 'incidencerate2'), (None, 'null')], default='', max_length=100, null=True, verbose_name='incidence_rate'),
        ),
        migrations.AlterField(
            model_name='dengue',
            name='lymp_d0',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dengue',
            name='myalgia',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), (None, 'null')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dengue',
            name='nausea',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), (None, 'null')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dengue',
            name='occ2',
            field=models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Officer', 'Officer'), ('Student', 'Student'), ('Other', 'Other'), (None, 'null')], default='', max_length=240, null=True, verbose_name='occupation'),
        ),
        migrations.AlterField(
            model_name='dengue',
            name='other_bleeding',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), (None, 'null')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dengue',
            name='other_mucosal_bleeding',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), (None, 'null')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dengue',
            name='petechiae',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), (None, 'null')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dengue',
            name='tourniquettest',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), (None, 'null')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), (None, 'null')], default='', max_length=10, null=True),
        ),
    ]
