# Generated by Django 3.0.10 on 2021-06-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20210628_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dengue',
            name='UD2',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), (None, 'null')], default='', max_length=100, null=True, verbose_name='UD2'),
        ),
        migrations.AlterField(
            model_name='dengue',
            name='hct_d0',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
