# Generated by Django 3.0.10 on 2021-08-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_auto_20210731_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'get_latest_by': 'updated_at', 'ordering': ['updated_at']},
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
